kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pv-claim
spec:
  storageClassName: standard # If not specified, the default storage class will be used
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi