apiVersion: v1
kind: Pod
metadata:
  name: ksql-server
  labels:
    app: ksql
    tier: server
spec:
  containers:
  - name: ksqldb-server
    image: confluentinc/ksqldb-server:0.28.2
    ports:
      - containerPort: 8088
    env:
      - name: KSQL_LISTENERS
        value: http://0.0.0.0:8088
      - name: KSQL_BOOTSTRAP_SERVERS
        value: kafka-headless.kafkanalytics.svc.cluster.local:9092
      - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
        value: "true"
      - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
        value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: ksql-server
spec:
  ports:
  - port: 8088
    protocol: TCP
  selector:
    app: ksql
    tier: server
---
apiVersion: v1
kind: Pod
metadata:
  name: ksql-cli
  labels:
    app: ksql
    tier: cli
spec:
  containers:
  - name: ksqldb-cli
    image: confluentinc/ksqldb-cli:0.28.2
    ports:
      - containerPort: 9000
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
---
apiVersion: v1
kind: Service
metadata:
  name: ksql-cli
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: ksql
    tier: cli