apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-redis-001
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 16M
  hostPath:
    path: /data/001