# redis configuration
# https://redis.io/docs/manual/config/
apiVersion: v1
kind: Secret
metadata:
  name: my-redis-config
type: Opaque
stringData:
  redis.conf: |-
    
    # AUTH
    requirepass "fabien-lamonarca"
    
    # PERSISTENCE : APPEND ONLY FILE (AOF)
    appendonly yes
    appendfilename "appendonly.aof"
    appenddirname "AOF"
    appendfsync everysec

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis-deployment
  labels:
    app: redis
  annotations:
    author: f.lamonarca
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        # docker image : https://registry.hub.docker.com/_/redis
        - name: redis
          image: redis:7.0.4
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config
              mountPath: "/etc/config"
              readOnly: true
            - name: redis-persistence
              mountPath: "/data/CUSTOM-AOF"
          command: ["redis-server", "/etc/config/redis.conf"]
      volumes:
        - name: redis-config
          secret:
            secretName: my-redis-config
        - name: redis-persistence
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: my-redis-svc
  annotations:
    author: f.lamonarca
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 6379

---
